package com.example.dynamodb.mapper.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;

/**
 * @description:
 * @author: LiuHu
 * @create: 2020/10/8
 **/
@DynamoDBTable(tableName = "Order")
@Data
public class Order {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBRangeKey(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "info")
    private String info;

    @DynamoDBAttribute
    @DynamoDBTypeConvertedTimestamp
    private Date createTime;
}
